career-stats-settings:
    data:
        initialVisited: true
        welcomedSeason: 16
    schemaVersion: 1
champ-select:
    data:
        skins:
            1: 1006
            10: 10000
            101: 101000
            103: 103000
            104: 104000
            105: 105000
            111: 111001
            113: 113000
            117: 117000
            12: 12000
            121: 121000
            134: 134000
            14: 14000
            143: 143007
            147: 147000
            154: 154024
            16: 16000
            161: 161000
            17: 17000
            18: 18000
            19: 19000
            20: 20000
            200: 200000
            201: 201033
            21: 21000
            22: 22000
            222: 222000
            223: 223000
            23: 23000
            235: 235000
            238: 238000
            24: 24033
            240: 240000
            25: 25010
            26: 26001
            266: 266000
            267: 267000
            27: 27000
            28: 28000
            29: 29006
            3: 3000
            30: 30017
            31: 31000
            32: 32000
            34: 34008
            35: 35000
            350: 350028
            36: 36000
            37: 37000
            4: 4000
            40: 40005
            412: 412013
            420: 420000
            427: 427000
            43: 43000
            44: 44000
            45: 45000
            48: 48000
            497: 497000
            498: 498000
            51: 51005
            526: 526000
            53: 53002
            54: 54000
            55: 55000
            555: 555009
            57: 57004
            58: 58018
            59: 59000
            62: 62000
            67: 67011
            711: 711000
            74: 74000
            76: 76000
            77: 77000
            78: 78022
            8: 8000
            80: 80000
            81: 81000
            86: 86000
            893: 893000
            895: 895000
            897: 897000
            9: 9000
            902: 902000
            98: 98000
            99: 99000
        spells:
            1020:
            - 4
            - 6
            1300:
            - 4
            - 14
            1700:
            - 2201
            - 2202
            1900:
            - 4
            - 6
            400:
            - 4
            - 14
            420:
            - 4
            - 7
            430:
            - 4
            - 3
            440:
            - 4
            - 12
            450:
            - 4
            - 32
            700:
            - 4
            - 3
            900:
            - 4
            - 14
    schemaVersion: 1
clash-tutorial:
    data:
        captainInviteStep: true
        captainLockinStep: true
        captainRewardStep: true
        captainRoleStep: true
        captainTicketStep: true
        initialized: true
        memberJoinTeamStep: true
        memberLockinStep: true
        memberRewardStep: true
        memberRoleStep: true
        memberTicketStep: true
        rosterDetailsModalLogoStep: true
        rosterDetailsModalNameTagStep: true
        smsButtonStep: true
        version: 2
    schemaVersion: 1
cosmetics-last-viewed-date:
    data:
        typeToLastOpenedDate:
            COMPANION: 1688295679
            TFT_DAMAGE_SKIN: 1686768524
            TFT_MAP_SKIN: 1678568348
    schemaVersion: 1
cosmetics-settings:
    data:
        companions:
            hideUnowned: true
    schemaVersion: 1
custom-spell-selections:
    data:
        custom-spell-selections:
            spell1: 4
            spell2: 7
    schemaVersion: 0
emotes:
    data:
        newEmotes:
        - 4536
        - 4535
        - 1492
        - 3003
        - 4516
        - 4075
    schemaVersion: 1
event-hub:
    data:
        lastSeenTokenBalance: 0
        lastSeenTokenShopOffersVersion: 693222939
        lastTimeSeen: "2024-08-19T14:36:07.114Z"
    schemaVersion: 1
event-shop:
    data:
        lastSeenTokenBalance: 60
        lastSeenTokenShopOffersVersion: 3048320223
        lastTimeSeen: "2024-03-10T19:10:14.124Z"
    schemaVersion: 1
lol-challenges:
    data:
        introModalShown: true
    schemaVersion: 1
lol-challenges-latest-level-up:
    data:
        lastLevelUpTime: 0
    schemaVersion: 1
lol-champ-select:
    data:
        championTradeToggleTooltipSeen: true
        favorites:
            bottom:
            - 147
            jungle:
            - 53
            support:
            - 235
            - 412
            - 117
            - 200
            - 40
            - 12
            - 267
            - 25
            - 89
            - 497
            - 34
            - 24
            - 31
            - 111
            - 78
            - 57
        positionSwapToggleTooltipSeen: true
        reportAndMutingTooltipShown: true
        runeRecommenderTutorialTipSeen: true
    schemaVersion: 0
lol-chat:
    data:
        chatFilterDisabled: true
        groupByProductShown: true
        hideDateDividers: false
        linkClickWarningEnabled: false
    schemaVersion: 1
lol-clash:
    data:
        clash-eat-tooltip-37221: true
    schemaVersion: 1
lol-collection-champions:
    data:
        groupingDropdownKey: "undefined"
        lastVisitTime: 1724184890502
        lcm-eat-seen: true
        sortingDropdownKey: "undefined"
        unownedFilter: "none"
    schemaVersion: 1
lol-collection-chromas:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1680957536476
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-collection-summoner-icons:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1680704303053
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-collection-wards:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1694638281849
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 3
lol-customizer-icons:
    data:
        lastVisitTime: 1724092448098
    schemaVersion: 1
lol-customizer-titles:
    data:
        lastVisitTime: 1716660021043
    schemaVersion: 1
lol-customizer-tokens:
    data:
        lastVisitTime: 1723664584004
    schemaVersion: 1
lol-general:
    data:
        top-nav-updates-eat-seen: true
        uploadCrashReports: true
    schemaVersion: 1
lol-home-hubs:
    data:
        lunar-revel-embed-2023:
            introThemeSelectWatched: "true"
            introWatched: "true"
        msi-embed-2023:
            introWatched: "true"
            showSpoilersSchedule: "true"
        space-groove-hub-2021:
            watchedIntro: true
        star-guardians-metagame-hub-2022:
            0: "[]"
            1: "13"
            2: "2"
            ambientAudioDisabled: "false"
            fallbackSaved: "true"
            introWatched: "true"
            motionDisabled: "false"
            tutorialWatched: "true"
        winterblessed-embed-2022:
            introWatched: "true"
        worlds-hub-2022:
            ambientAudioDisabled: "true"
            introSkinLineWatched: "true"
            introWorldsEventPassWatched: "true"
            motionDisabled: "false"
    schemaVersion: 1
lol-honor:
    data:
        recallReleaseNotified: true
    schemaVersion: 1
lol-leagues:
    data:
        FINAL_RANK_ONE_OF_SEASON-RANKED_FLEX_SR: 15
        FINAL_RANK_ONE_OF_SEASON-RANKED_SOLO_5x5: 15
        FIRST_CHALLENGER_OF_SEASON-RANKED_FLEX_SR: 16
        FIRST_CHALLENGER_OF_SEASON-RANKED_SOLO_5x5: 16
        hasSeenFlexRestrictionModal: true
        last-split-end-notification: 15
        last-split-start-modal: 13.100000
        season-memorial-modal: 15
        season-start-takeover:
            season: 16
    schemaVersion: 1
lol-loot:
    data:
        mass-disenchant-tooltip-seen: true
    schemaVersion: 1
lol-notifications:
    data:
        disableCollectionsNotifications: true
        disableEsportsNotifications: true
        rgmNotificationTimestamp: 1711844219833
    schemaVersion: 1
lol-npe-first-touch:
    data:
        modeSelected: "summoners-rift"
    schemaVersion: 1
lol-npe-rewards:
    data:
        challenges:
            allMissionsCompleted: true
            totalCount: 8
        login:
            allRewardsClaimed: true
            lastCompletedMissionDate: 1619389760000
            lastCompletedMissionInternalName: "npe_rewards_login_v1_step7"
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: true
        hasSkippedTutorialPath: true
        shouldSeeNewPlayerExperience: true
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-perks:
    data:
        playerFlashOnFPreference: false
        shouldIncludeSummonerSpells: true
    schemaVersion: 1
lol-player-behavior:
    data:
        codeOfConductAccepted: true
    schemaVersion: 0
lol-premade-voice:
    data:
        autoJoin: false
        inputMode: "voiceActivity"
        muteOnConnect: true
        pushToTalkKey: "[<Unbound>]"
        showFirstExperienceInGame: true
        showFirstExperienceInLCU: false
    schemaVersion: 1
lol-profiles:
    data:
        ranked-reference-modal-login-seen-for-season: 16
    schemaVersion: 0
lol-quick-play:
    data:
        slots:
        -   championId: 350
            perks: "{\"perkIds\":[8214,8226,8210,8237,8453,8446,5007,5008,5001],\"perkStyle\":8200,\"perkSubStyle\":8400}"
            positionPreference: "UTILITY"
            skinId: 350028
            spell1: 7
            spell2: 12
        -   championId: 200
            perks: "{\"perkIds\":[8008,9111,9104,8014,8347,8304,5005,5008,5001],\"perkStyle\":8000,\"perkSubStyle\":8300}"
            positionPreference: "JUNGLE"
            skinId: 200000
            spell1: 4
            spell2: 11
    schemaVersion: 1
lol-skins-viewer:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1708891563968
        sortingDropdownKey: "acquisitionDate"
        unownedFilter: false
    schemaVersion: 2
lol-tft:
    data:
        iconOverride: "summonerIcon"
        lastTFTBPSeen: "7b0da811-576c-4899-a967-8e2dbbdac9a2"
        lastTftGameQueueId: 1090
        lastTftSetNameSeen: "TFTSet12"
        previouslySeenSeasons: "TFTBattlepass_Fates2_Series,TFT7_Series,TFT7_5_Series,TFT8_Series,TFT8_5_Series,1686765600000,1694628000000,1706130000000"
        seenOfferIds:
            storeOfferIds:
            - "29782c0d-c3f6-4374-8b29-43da99a06b24"
            - "e5d3eecb-a76d-49d1-b6e3-6a3bd315f2a5"
            tacticianOfferIds:
            - "8054bbc4-92f1-4ddb-98f4-0b33ccd1de51"
        tftEmeraldModalSeen: true
    schemaVersion: 1
lol-tutorial:
    data:
        CustomButtonPopupViewed: true
        Map21_NEXUSBLITZ_TutorialSeen: true
        Map22_TFT_TFT_PAIRS_TutorialSeen: true
        Map22_TFT_TutorialSeen: true
        Map23_Playbook_TutorialSeen: true
        Map30_CHERRY_TutorialSeen: true
        Playbook_CTASeen_TFT9: true
        championSelectRunesTooltipSeenCount: 10
        npeRewardsV1IntroSeen: true
        perksCreateNewPageSeen: true
        perksPresetPagesSeen: true
        perksPrimaryPathSeen: true
        perksStatModsSeen: true
    schemaVersion: 1
missions-settings:
    data:
        selected_series: "all_missions"
    schemaVersion: 0
partiesPositionPreferences:
    data:
        firstPreference: "UTILITY"
        secondPreference: "BOTTOM"
    schemaVersion: 0
personalized-offers:
    data:
        lastViewedTimestamp: "2022-08-08T17:04:21.313Z"
    schemaVersion: 1
ranked-eos-notification-12-RANKED_SOLO_5x5-FIRST_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-12-RANKED_SOLO_5x5-SEASON_ENDED:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-12-RANKED_SOLO_5x5-SECOND_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-13-RANKED_SOLO_5x5-SECOND_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-14-RANKED_SOLO_5x5-FIRST_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-14-RANKED_SOLO_5x5-SECOND_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-15-RANKED_SOLO_5x5-FIRST_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
ranked-eos-notification-15-RANKED_SOLO_5x5-SECOND_WARNING:
    data:
        notificationShown: true
    schemaVersion: 1
yourshop:
    data:
        lastViewedTimestamp: "2024-08-18T15:08:46.651Z"
    schemaVersion: 1
